apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-two-containers
  labels:
    app: two-containers
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: two-containers
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: two-containers
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        {{- if .Values.customIndex.enabled }}
        volumeMounts:
        - name: custom-index
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        {{- end }}
      {{- if .Values.customIndex.enabled }}
      volumes:
      - name: custom-index
        configMap:
          name: {{ .Release.Name }}-index
      {{- end }}